// Master list of Indian banks (public / private / small finance / payments /
// major co-operative & foreign banks operating in India).
export const INDIAN_BANKS: string[] = [
  "State Bank of India",
  "Punjab National Bank",
  "Bank of Baroda",
  "Bank of India",
  "Canara Bank",
  "Union Bank of India",
  "Indian Bank",
  "Central Bank of India",
  "Indian Overseas Bank",
  "UCO Bank",
  "Bank of Maharashtra",
  "Punjab & Sind Bank",
  "HDFC Bank",
  "ICICI Bank",
  "Axis Bank",
  "Kotak Mahindra Bank",
  "IndusInd Bank",
  "Yes Bank",
  "IDFC FIRST Bank",
  "IDBI Bank",
  "Federal Bank",
  "South Indian Bank",
  "Karur Vysya Bank",
  "Karnataka Bank",
  "City Union Bank",
  "Tamilnad Mercantile Bank",
  "RBL Bank",
  "Bandhan Bank",
  "DCB Bank",
  "CSB Bank",
  "Dhanlaxmi Bank",
  "Jammu & Kashmir Bank",
  "Nainital Bank",
  "Bharat Co-operative Bank",
  "Saraswat Co-operative Bank",
  "Cosmos Co-operative Bank",
  "Abhyudaya Co-operative Bank",
  "SVC Co-operative Bank",
  "TJSB Sahakari Bank",
  "Kalupur Commercial Co-operative Bank",
  "NKGSB Co-operative Bank",
  "Janata Sahakari Bank",
  "Punjab & Maharashtra Co-operative Bank",
  "Apna Sahakari Bank",
  "Citizen Credit Co-operative Bank",
  "Rajkot Nagarik Sahakari Bank",
  "Mehsana Urban Co-operative Bank",
  "Ahmedabad Mercantile Co-operative Bank",
  "Surat People's Co-operative Bank",
  "Shamrao Vithal Co-operative Bank",
  "AU Small Finance Bank",
  "Equitas Small Finance Bank",
  "Ujjivan Small Finance Bank",
  "Jana Small Finance Bank",
  "Suryoday Small Finance Bank",
  "ESAF Small Finance Bank",
  "Fincare Small Finance Bank",
  "Utkarsh Small Finance Bank",
  "Capital Small Finance Bank",
  "North East Small Finance Bank",
  "Shivalik Small Finance Bank",
  "Unity Small Finance Bank",
  "Slice Small Finance Bank",
  "Airtel Payments Bank",
  "India Post Payments Bank",
  "Fino Payments Bank",
  "Paytm Payments Bank",
  "Jio Payments Bank",
  "NSDL Payments Bank",
  "Citibank India",
  "HSBC India",
  "Standard Chartered Bank",
  "Deutsche Bank India",
  "DBS Bank India",
  "Barclays Bank India",
  "BNP Paribas India",
  "Bank of America India",
  "JPMorgan Chase Bank India",
  "MUFG Bank India",
  "Mizuho Bank India",
  "Sumitomo Mitsui Banking Corporation",
  "SBM Bank India",
  "CTBC Bank India",
  "Credit Agricole Corporate & Investment Bank",
  "Societe Generale India",
  "Emirates NBD Bank",
  "First Abu Dhabi Bank",
  "Qatar National Bank",
  "Bank of Ceylon",
  "Doha Bank",
  "Woori Bank India",
  "Shinhan Bank India",
  "KEB Hana Bank India",
  "Industrial Bank of Korea",
  "Bank of China India",
  "Sberbank India",
  "American Express Banking Corp",
  "Kerala Gramin Bank",
  "Baroda Rajasthan Kshetriya Gramin Bank",
  "Uttar Pradesh Gramin Bank",
  "Andhra Pragathi Grameena Bank",
  "Karnataka Gramin Bank",
  "Madhya Pradesh Gramin Bank",
];

export const OTHER_BANK = "Other Bank";

export const BANK_OPTIONS: string[] = [...INDIAN_BANKS, OTHER_BANK];
